---
# Ruolo: tailscale - sola installazione; autenticazione interattiva separata
# Documentation in roles/tailscale/README.md

tailscale_install: false
tailscale_key_fingerprint: 2596A99EAAB33821893C0A79458CA832957F5868
